# Generated by Django 5.1.1 on 2024-09-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stm_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(blank=True, max_length=255, null=True)),
                ('integer_limit', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
