# Generated by Django 5.1.1 on 2024-09-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stm_generator', '0003_file_datatypes_created_datatypes_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageLinks',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('link_name', models.TextField(blank=True)),
                ('link_mapping', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('button_style', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
