# Generated by Django 5.1.1 on 2024-09-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stm_generator', '0004_homepagelinks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='File',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='file',
            name='File_Name',
        ),
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='homepagelinks',
            name='button_style',
            field=models.TextField(blank=True, default='btn btn-primary'),
        ),
        migrations.AddField(
            model_name='file',
            name='file_Name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
